### ISSUE TITLE
Design semantics and minimal predicate set

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/chamber-lang#11]
Designing semantics and predicates.
Purposes are to design OVM. It includes client-side and smart contract side.

### Tasks

- Re-define Quantifier
- eval(IsDeprecated)
- `aaa.bbb` operator(It's same as ∃bbb: getInput(aaa, 0))`

### References

https://github.com/cryptoeconomicslab/plasma-rust-framework/issues/268#issue-510008407
https://github.com/cryptoeconomicslab/wakkanay/issues/20

**Comment by syuhei176** [comment]
# Reminded Tasks

- [ ] Define predicate set
- [ ] write compile logic
- [ ] Solidity
- [ ] JSON(Rust, Ts)

**Comment by syuhei176** [comment]
I did these tasks through writing [compiler](https://github.com/cryptoeconomicslab/chamber-lang/tree/master/examples).

**Comment by syuhei176** [comment]
### Result

* In smart contract side, we don't need quantifier
* operator predicate have isValidChallenge and decideTrue methods
* atomic proposition predicate have decide and decideTrue methods. `decide` returns boolean value which is result of decision. decideTrue store result in UAC.
